CPPFLAGS	:= -g -Wall -std=c++17 -pedantic
LDFLAGS	:=
LDLIBS	:=

.PHONY: all clean
all: ColoringGraph.x

%.x: %.o
	$(CXX) $(LDFLAGS) -o $@ $^ $(LDLIBS)
%.o: %.cpp %.hpp
	$(CXX) $(CPPLAGS) -c -o $@ $<

ColoringGraph.x: ColoringGraph.o
ColoringGraph.o: ColoringGraph.cpp Graph.hpp

clean:
	$(RM) *.[ox]